// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GithubSearchServiceClient is the client API for GithubSearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GithubSearchServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type githubSearchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGithubSearchServiceClient(cc grpc.ClientConnInterface) GithubSearchServiceClient {
	return &githubSearchServiceClient{cc}
}

func (c *githubSearchServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/GithubSearchService.GithubSearchService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GithubSearchServiceServer is the server API for GithubSearchService service.
// All implementations must embed UnimplementedGithubSearchServiceServer
// for forward compatibility
type GithubSearchServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedGithubSearchServiceServer()
}

// UnimplementedGithubSearchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGithubSearchServiceServer struct {
}

func (UnimplementedGithubSearchServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedGithubSearchServiceServer) mustEmbedUnimplementedGithubSearchServiceServer() {}

// UnsafeGithubSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GithubSearchServiceServer will
// result in compilation errors.
type UnsafeGithubSearchServiceServer interface {
	mustEmbedUnimplementedGithubSearchServiceServer()
}

func RegisterGithubSearchServiceServer(s grpc.ServiceRegistrar, srv GithubSearchServiceServer) {
	s.RegisterService(&GithubSearchService_ServiceDesc, srv)
}

func _GithubSearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubSearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GithubSearchService.GithubSearchService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubSearchServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GithubSearchService_ServiceDesc is the grpc.ServiceDesc for GithubSearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GithubSearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GithubSearchService.GithubSearchService",
	HandlerType: (*GithubSearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _GithubSearchService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/githubSearch.proto",
}
